version: 2

sources:
  - name: raw
    schema: raw
    database: raw
    tables:
      - name: raw___insta_aisles
      - name: raw___insta_departments
      - name: raw___insta_products
      - name: raw___insta_orders
      - name: raw___insta_order_products_prior
      - name: raw___insta_order_products_train
