version: 2

models:
  - name: stg_grp3_instacart_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: user_id
        tests: [not_null]

  - name: stg_grp3_instacart_products
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: stg_grp3_instacart_aisles
    columns:
      - name: aisle_id
        tests: [not_null, unique]

  - name: stg_grp3_instacart_departments
    columns:
      - name: department_id
        tests: [not_null, unique]

  - name: stg_grp3_instacart_order_products_prior
    columns:
      - name: order_id
        tests: [not_null]

  - name: stg_grp3_instacart_order_products_train
    columns:
      - name: order_id
        tests: [not_null]
