version: 2


models:
  - name: stg_grp3_instacart_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: order_dow
        tests:
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5, 6]  
      - name: order_hour_of_day
        tests:
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]


  - name: stg_grp3_instacart_products
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: stg_grp3_instacart_aisles
    columns:
      - name: aisle_id
        tests: [not_null, unique]

  - name: stg_grp3_instacart_departments
    columns:
      - name: department_id
        tests: [not_null, unique]

  - name: stg_grp3_instacart_order_products_prior
    columns:
      - name: order_id
        tests: [not_null]

  - name: stg_grp3_instacart_order_products_train
    columns:
      - name: order_id
        tests: [not_null]
